[package]
name = "reflow_cv_ops"
version = "0.1.0"
edition = "2021"

[dependencies]
actor_macro = { path = "../actor_macro" }
anyhow = { workspace = true }
flume = { workspace = true }
reflow_actor = { path = "../reflow_actor" }
reflow_media_codec = { path = "../reflow_media_codec" }
reflow_media_types = { path = "../reflow_media_types" }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
