export const EditorEvents = Object.freeze({
    READY: "READY",
    INIT: "INIT",
    GRAPH_LOADED: "GRAPH_LOADED",
    ADD_NODE: "ADD_NODE",
    ADD_EDGE: "ADD_EDGE",
    ADD_GROUP: "ADD_GROUP",
    ADD_IIP: "ADD_IIP",
    UPDATE_GROUP_METADATA: "UPDATE_GROUP_METADATA",
    UPDATE_NODE_METADATA: "UPDATE_NODE_METADATA"
});