#![allow(clippy::all, unused_imports, dead_code)]

//! Auto-generated API actor modules.
//!
//! Generated by api-schema-gen codegen — do not edit manually.

pub mod api_registry;

pub mod accuweather;
pub mod adopt_a_pet;
pub mod adyen;
pub mod airtable;
pub mod alphavantage;
pub mod amplitude;
pub mod anthropic;
pub mod asana;
pub mod auth0;
pub mod aws_dynamodb;
pub mod aws_s3;
pub mod binance;
pub mod bitbucket;
pub mod braintree;
pub mod circleci;
pub mod clickup;
pub mod cloudflare;
pub mod cohere;
pub mod coinbase;
pub mod currencyapi;
pub mod discord;
pub mod dropbox;
pub mod facebook;
pub mod firebase;
pub mod freshworks;
pub mod giphy;
pub mod github;
pub mod gitlab;
pub mod google_analytics;
pub mod google_maps;
pub mod google_sheets;
pub mod here;
pub mod hubspot;
pub mod hugging_face;
pub mod instagram;
pub mod intercom;
pub mod ipgeolocation;
pub mod jira;
pub mod leaksapi;
pub mod linear;
pub mod linkedin;
pub mod mailgun;
pub mod mapbox;
pub mod microsoft_teams;
pub mod mixpanel;
pub mod monday;
pub mod mongodb_atlas;
pub mod nasa;
pub mod netlify;
pub mod newsapi;
pub mod notion;
pub mod nytimes;
pub mod okta;
pub mod omdb;
pub mod openai;
pub mod openweathermap;
pub mod paypal;
pub mod pexels;
pub mod pinterest;
pub mod pipedrive;
pub mod posthog;
pub mod razorpay;
pub mod replicate;
pub mod salesforce;
pub mod segment;
pub mod sendgrid;
pub mod shopify;
pub mod slack;
pub mod spoonacular;
pub mod spotify;
pub mod square;
pub mod stability_ai;
pub mod stripe;
pub mod supabase;
pub mod telegram;
pub mod tmdb;
pub mod tomtom;
pub mod trello;
pub mod twilio;
pub mod twitch;
pub mod twitter;
pub mod unsplash;
pub mod vercel;
pub mod vonage;
pub mod weatherbit;
pub mod whatsapp_business;
pub mod youtube;
pub mod zoom;

/// Convert a Message to a string for use in query params / path params.
pub(crate) fn message_to_str(msg: &crate::Message) -> String {
    match msg {
        crate::Message::String(s) => s.as_ref().clone(),
        crate::Message::Integer(i) => i.to_string(),
        crate::Message::Float(f) => f.to_string(),
        crate::Message::Boolean(b) => b.to_string(),
        other => serde_json::to_string(other).unwrap_or_default(),
    }
}
