#![allow(clippy::all, unused_imports, dead_code)]

//! Auto-generated API actors for Unsplash
//!
//! Service: Unsplash (unsplash)
//! Free high-resolution photos
//!
//! Required env var: UNSPLASH_API_KEY (OAuth2 access token)
//!
//! Generated by api-schema-gen codegen — do not edit manually.

use crate::{Actor, ActorBehavior, Message, Port};
use actor_macro::actor;
use anyhow::{Error, Result};
use reflow_actor::{message::EncodableValue, ActorContext};
use serde_json::{json, Value};
use std::collections::HashMap;
use std::time::Duration;

const BASE_URL: &str = "https://api.unsplash.com";
const ENV_KEY: &str = "UNSPLASH_API_KEY";

/// Apply authentication to the request builder.
fn apply_auth(config: &reflow_actor::ActorConfig, mut builder: reqwest::RequestBuilder) -> Result<reqwest::RequestBuilder> {
    let credential = config.get_config_or_env(ENV_KEY)
        .ok_or_else(|| anyhow::anyhow!("Missing env var: {}", ENV_KEY))?;
    builder = builder.header("Authorization", format!("Bearer {}", credential));
    Ok(builder)
}

/// search photos via Unsplash API
///
/// Method: GET /search/photos
#[actor(
    UnsplashSearchPhotosActor,
    inports::<100>(query, per_page, page),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_search_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/search/photos".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("query") {
        query_pairs.push(("query", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /search/photos failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// read photo via Unsplash API
///
/// Method: GET /photos/{id}
#[actor(
    UnsplashReadPhotoActor,
    inports::<100>(id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_photo(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/photos/{id}".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /photos/{{id}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get the current authenticated user's profile
///
/// Method: GET /me
#[actor(
    UnsplashReadCurrentUserActor,
    inports::<100>(trigger),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_current_user(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/me".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /me failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Update the current authenticated user's profile
///
/// Method: PUT /me
#[actor(
    UnsplashUpdateCurrentUserActor,
    inports::<100>(username, first_name, last_name, email, url, location, bio, instagram_username),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_update_current_user(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/me".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.put(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut body = serde_json::Map::new();
    if let Some(val) = inputs.get("username") {
        body.insert("username".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("first_name") {
        body.insert("first_name".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("last_name") {
        body.insert("last_name".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("email") {
        body.insert("email".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("url") {
        body.insert("url".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("location") {
        body.insert("location".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("bio") {
        body.insert("bio".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("instagram_username") {
        body.insert("instagram_username".to_string(), val.clone().into());
    }
    if !body.is_empty() {
        builder = builder.json(&serde_json::Value::Object(body));
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("PUT /me failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve public details on a given user
///
/// Method: GET /users/{username}
#[actor(
    UnsplashReadUserActor,
    inports::<100>(username),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_user(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a single user's portfolio link
///
/// Method: GET /users/{username}/portfolio
#[actor(
    UnsplashReadUserPortfolioActor,
    inports::<100>(username),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_user_portfolio(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}/portfolio".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}}/portfolio failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a list of photos uploaded by a user
///
/// Method: GET /users/{username}/photos
#[actor(
    UnsplashListUserPhotosActor,
    inports::<100>(username, page, per_page, order_by, stats, resolution, quantity, orientation),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_user_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}/photos".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("order_by") {
        query_pairs.push(("order_by", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("stats") {
        query_pairs.push(("stats", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("resolution") {
        query_pairs.push(("resolution", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("quantity") {
        query_pairs.push(("quantity", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("orientation") {
        query_pairs.push(("orientation", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}}/photos failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a list of photos liked by a user
///
/// Method: GET /users/{username}/likes
#[actor(
    UnsplashListUserLikedPhotosActor,
    inports::<100>(username, page, per_page, order_by, orientation),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_user_liked_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}/likes".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("order_by") {
        query_pairs.push(("order_by", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("orientation") {
        query_pairs.push(("orientation", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}}/likes failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a list of collections created by the user
///
/// Method: GET /users/{username}/collections
#[actor(
    UnsplashListUserCollectionsActor,
    inports::<100>(username, page, per_page),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_user_collections(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}/collections".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}}/collections failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve consolidated number of downloads, views and likes for all user's photos
///
/// Method: GET /users/{username}/statistics
#[actor(
    UnsplashReadUserStatisticsActor,
    inports::<100>(username, resolution, quantity),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_user_statistics(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/users/{username}/statistics".to_string();
    if let Some(val) = inputs.get("username") {
        endpoint = endpoint.replace("{{username}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("resolution") {
        query_pairs.push(("resolution", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("quantity") {
        query_pairs.push(("quantity", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /users/{{username}}/statistics failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a single page from the Editorial feed
///
/// Method: GET /photos
#[actor(
    UnsplashListPhotosActor,
    inports::<100>(page, per_page, order_by, content_filter),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/photos".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("order_by") {
        query_pairs.push(("order_by", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("content_filter") {
        query_pairs.push(("content_filter", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /photos failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve statistics for a single photo
///
/// Method: GET /photos/{id}/statistics
#[actor(
    UnsplashReadPhotoStatisticsActor,
    inports::<100>(id, resolution, quantity),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_photo_statistics(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/photos/{id}/statistics".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("resolution") {
        query_pairs.push(("resolution", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("quantity") {
        query_pairs.push(("quantity", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /photos/{{id}}/statistics failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Track a photo download (triggers download tracking as required by API guidelines)
///
/// Method: GET /photos/{id}/download
#[actor(
    UnsplashDownloadPhotoActor,
    inports::<100>(id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_download_photo(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/photos/{id}/download".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /photos/{{id}}/download failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Update a photo on behalf of the logged-in user
///
/// Method: PUT /photos/{id}
#[actor(
    UnsplashUpdatePhotoActor,
    inports::<100>(id, description, show_on_profile, tags, location, exif),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_update_photo(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/photos/{id}".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.put(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut body = serde_json::Map::new();
    if let Some(val) = inputs.get("description") {
        body.insert("description".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("show_on_profile") {
        body.insert("show_on_profile".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("tags") {
        body.insert("tags".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("location") {
        body.insert("location".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("exif") {
        body.insert("exif".to_string(), val.clone().into());
    }
    if !body.is_empty() {
        builder = builder.json(&serde_json::Value::Object(body));
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("PUT /photos/{{id}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Search collections by keyword
///
/// Method: GET /search/collections
#[actor(
    UnsplashSearchCollectionsActor,
    inports::<100>(query, page, per_page),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_search_collections(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/search/collections".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("query") {
        query_pairs.push(("query", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /search/collections failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Search users by keyword
///
/// Method: GET /search/users
#[actor(
    UnsplashSearchUsersActor,
    inports::<100>(query, page, per_page),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_search_users(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/search/users".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("query") {
        query_pairs.push(("query", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /search/users failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a single page from the list of all collections
///
/// Method: GET /collections
#[actor(
    UnsplashListCollectionsActor,
    inports::<100>(page, per_page),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_collections(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /collections failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a single collection
///
/// Method: GET /collections/{id}
#[actor(
    UnsplashReadCollectionActor,
    inports::<100>(id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_collection(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{id}".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /collections/{{id}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a collection's photos
///
/// Method: GET /collections/{id}/photos
#[actor(
    UnsplashListCollectionPhotosActor,
    inports::<100>(id, page, per_page, orientation),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_collection_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{id}/photos".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("orientation") {
        query_pairs.push(("orientation", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /collections/{{id}}/photos failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a list of collections related to this one
///
/// Method: GET /collections/{id}/related
#[actor(
    UnsplashListCollectionRelatedActor,
    inports::<100>(id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_collection_related(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{id}/related".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /collections/{{id}}/related failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Create a new collection (requires write_collections scope)
///
/// Method: POST /collections
#[actor(
    UnsplashCreateCollectionActor,
    inports::<100>(title, description, private),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_create_collection(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.post(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut body = serde_json::Map::new();
    if let Some(val) = inputs.get("title") {
        body.insert("title".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("description") {
        body.insert("description".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("private") {
        body.insert("private".to_string(), val.clone().into());
    }
    if !body.is_empty() {
        builder = builder.json(&serde_json::Value::Object(body));
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("POST /collections failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Update an existing collection (requires write_collections scope)
///
/// Method: PUT /collections/{id}
#[actor(
    UnsplashUpdateCollectionActor,
    inports::<100>(id, title, description, private),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_update_collection(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{id}".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.put(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut body = serde_json::Map::new();
    if let Some(val) = inputs.get("title") {
        body.insert("title".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("description") {
        body.insert("description".to_string(), val.clone().into());
    }
    if let Some(val) = inputs.get("private") {
        body.insert("private".to_string(), val.clone().into());
    }
    if !body.is_empty() {
        builder = builder.json(&serde_json::Value::Object(body));
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("PUT /collections/{{id}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Delete a collection (requires write_collections scope)
///
/// Method: DELETE /collections/{id}
#[actor(
    UnsplashDeleteCollectionActor,
    inports::<100>(id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_delete_collection(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{id}".to_string();
    if let Some(val) = inputs.get("id") {
        endpoint = endpoint.replace("{{id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.delete(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("DELETE /collections/{{id}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Add a photo to a collection (requires write_collections scope)
///
/// Method: POST /collections/{collection_id}/add
#[actor(
    UnsplashCreateCollectionPhotoActor,
    inports::<100>(collection_id, photo_id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_create_collection_photo(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{collection_id}/add".to_string();
    if let Some(val) = inputs.get("collection_id") {
        endpoint = endpoint.replace("{{collection_id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.post(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut body = serde_json::Map::new();
    if let Some(val) = inputs.get("photo_id") {
        body.insert("photo_id".to_string(), val.clone().into());
    }
    if !body.is_empty() {
        builder = builder.json(&serde_json::Value::Object(body));
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("POST /collections/{{collection_id}}/add failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Remove a photo from a collection (requires write_collections scope)
///
/// Method: DELETE /collections/{collection_id}/remove
#[actor(
    UnsplashDeleteCollectionPhotoActor,
    inports::<100>(collection_id, photo_id),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_delete_collection_photo(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/collections/{collection_id}/remove".to_string();
    if let Some(val) = inputs.get("collection_id") {
        endpoint = endpoint.replace("{{collection_id}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.delete(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("photo_id") {
        query_pairs.push(("photo_id", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("DELETE /collections/{{collection_id}}/remove failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a single page from the list of all topics
///
/// Method: GET /topics
#[actor(
    UnsplashListTopicsActor,
    inports::<100>(ids, page, per_page, order_by),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_topics(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/topics".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("ids") {
        query_pairs.push(("ids", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("order_by") {
        query_pairs.push(("order_by", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /topics failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a single topic
///
/// Method: GET /topics/{id_or_slug}
#[actor(
    UnsplashReadTopicActor,
    inports::<100>(id_or_slug),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_topic(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/topics/{id_or_slug}".to_string();
    if let Some(val) = inputs.get("id_or_slug") {
        endpoint = endpoint.replace("{{id_or_slug}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /topics/{{id_or_slug}} failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Retrieve a topic's photos
///
/// Method: GET /topics/{id_or_slug}/photos
#[actor(
    UnsplashListTopicPhotosActor,
    inports::<100>(id_or_slug, page, per_page, orientation, order_by),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_list_topic_photos(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/topics/{id_or_slug}/photos".to_string();
    if let Some(val) = inputs.get("id_or_slug") {
        endpoint = endpoint.replace("{{id_or_slug}}", &super::message_to_str(val));
    }

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut query_pairs: Vec<(&str, String)> = Vec::new();
    if let Some(val) = inputs.get("page") {
        query_pairs.push(("page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("per_page") {
        query_pairs.push(("per_page", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("orientation") {
        query_pairs.push(("orientation", super::message_to_str(val)));
    }
    if let Some(val) = inputs.get("order_by") {
        query_pairs.push(("order_by", super::message_to_str(val)));
    }
    if !query_pairs.is_empty() {
        builder = builder.query(&query_pairs);
    }

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /topics/{{id_or_slug}}/photos failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get a list of counts for all of Unsplash
///
/// Method: GET /stats
#[actor(
    UnsplashReadStatsTotalsActor,
    inports::<100>(trigger),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_stats_totals(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/stats".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /stats failed: {}", e).into()));
        }
    }

    Ok(output)
}

/// Get the overall Unsplash stats for the past 30 days
///
/// Method: GET /stats/month
#[actor(
    UnsplashReadStatsMonthActor,
    inports::<100>(trigger),
    outports::<50>(response, error),
    state(MemoryState)
)]
pub async fn unsplash_read_stats_month(context: ActorContext) -> Result<HashMap<String, Message>, Error> {
    let inputs = context.get_payload();
    let actor_config = context.get_config();

    let mut endpoint = "/stats/month".to_string();

    let url = format!("{}{}", BASE_URL.trim_end_matches('/'), endpoint);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()?;

    let mut builder = client.get(&url);
    builder = builder.header("Content-Type", "application/json");
    builder = apply_auth(actor_config, builder)?;

    let mut output = HashMap::new();
    match builder.send().await {
        Ok(resp) => {
            let status = resp.status().as_u16();
            let headers: HashMap<String, String> = resp.headers()
                .iter()
                .filter_map(|(k, v)| v.to_str().ok().map(|val| (k.to_string(), val.to_string())))
                .collect();
            let body_text = resp.text().await.unwrap_or_default();
            let body_value: Value = serde_json::from_str(&body_text).unwrap_or(Value::String(body_text));
            output.insert("response".to_string(), Message::object(EncodableValue::from(json!({
                "status": status,
                "headers": headers,
                "body": body_value,
            }))));
        }
        Err(e) => {
            output.insert("error".to_string(), Message::Error(format!("GET /stats/month failed: {}", e).into()));
        }
    }

    Ok(output)
}

