import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SonatypeHost

plugins {
    id("java-library")
    kotlin("jvm") version "1.9.24"
    // Handles POM, sources/javadoc jars, GPG signing, and the
    // staging-then-release dance against the Sonatype Central Portal.
    // See sdk/jvm/PUBLISHING.md for the one-time account + key setup.
    id("com.vanniktech.maven.publish") version "0.30.0"
    // Generates the HTML API reference that ships as the
    // `-javadoc.jar` and is rendered on javadoc.io. We feed it the
    // SDK README as the module landing page so javadoc.io shows the
    // full README content (Maven Central's overview only renders
    // POM metadata and can't display markdown).
    id("org.jetbrains.dokka") version "1.9.20"
}

group = "ai.offbit"
version = "0.2.4"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
    // sources jar is generated by the maven-publish plugin; declaring
    // it here too produces a duplicate Jar task.
}

repositories {
    mavenCentral()
}

dependencies {
    // Kotlin stdlib is pulled in automatically by the kotlin("jvm") plugin.
    // Coroutines are an opt-in convenience used by the Kotlin suspend /
    // Flow adapters. Users who don't want coroutines can omit them.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")

    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
    jvmToolchain(17)
}

// Maven Central requires a -javadoc.jar but JDK 9+ runs javadoc with
// strict doclint by default — any broken @link or missing @param
// fails the publish task. Disable doclint so the publish job is not
// gated on perfect javadoc.
tasks.withType<Javadoc>().configureEach {
    (options as StandardJavadocDocletOptions).addBooleanOption("Xdoclint:none", true)
}

// Point the JVM at the locally built native library so tests can run
// without installing it globally.
val nativeLibPath = rootDir.resolve("src/native/target/release/libreflow_rt_jvm.dylib")

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    systemProperty("reflow.native.lib", nativeLibPath.absolutePath)
}

// Convenience task that builds the Rust side first.
val buildNative by tasks.registering(Exec::class) {
    workingDir = rootDir.resolve("src/native")
    commandLine("cargo", "build", "--release")
}
tasks.named("compileJava") { dependsOn(buildNative) }
tasks.named("test") { dependsOn(buildNative) }

// ─── Dokka — README as module overview ────────────────────────────────────
//
// Dokka's `includes.from(...)` file is rendered on the module's landing
// page. The first line MUST be `# Module <name>` for Dokka to attribute
// it correctly. Synthesize the file from README.md at build time so the
// README stays single-source.

val prepareDokkaIncludes by tasks.registering {
    val src = file("README.md")
    val dst = layout.buildDirectory.file("dokka-includes/Module.md")
    inputs.file(src)
    outputs.file(dst)
    doLast {
        val out = dst.get().asFile
        out.parentFile.mkdirs()
        out.writeText("# Module reflow\n\n" + src.readText())
    }
}

tasks.dokkaHtml.configure {
    dependsOn(prepareDokkaIncludes)
    moduleName.set("reflow")
    dokkaSourceSets.named("main") {
        includes.from(layout.buildDirectory.file("dokka-includes/Module.md"))
        // Source links so reading a function in the rendered docs
        // jumps to the corresponding GitHub blob.
        sourceLink {
            localDirectory.set(file("src/main"))
            remoteUrl.set(uri("https://github.com/offbit-ai/reflow/blob/main/sdk/jvm/src/main").toURL())
            remoteLineSuffix.set("#L")
        }
    }
}

// ─── Maven Central publishing ──────────────────────────────────────────────
//
// The actual upload runs in CI (.github/workflows/publish-jvm.yml) where
// the Sonatype + GPG secrets are wired in as ORG_GRADLE_PROJECT_* env
// vars. Locally `./gradlew publishToMavenLocal` will write a signed jar
// to ~/.m2 if you have a key configured; without a key it produces an
// unsigned jar (good for smoke-testing the bundle layout).

mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, automaticRelease = false)
    signAllPublications()

    coordinates("ai.offbit", "reflow", project.version.toString())

    // Build the `-javadoc.jar` from `dokkaHtml` instead of the empty
    // stub. This is what javadoc.io serves at
    // https://javadoc.io/doc/ai.offbit/reflow/latest — the SDK README
    // becomes the landing page (see prepareDokkaIncludes above), with
    // every Java + Kotlin symbol cross-linked underneath.
    configure(JavaLibrary(javadocJar = JavadocJar.Dokka("dokkaHtml"), sourcesJar = true))

    pom {
        name.set("Reflow JVM SDK")
        description.set(
            "JVM bindings (Java + Kotlin) for the Reflow runtime — a modular " +
                "flow-based programming runtime built on the actor model."
        )
        url.set("https://github.com/offbit-ai/reflow")
        inceptionYear.set("2026")
        licenses {
            license {
                name.set("MIT OR Apache-2.0")
                url.set("https://github.com/offbit-ai/reflow/blob/main/LICENSE")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("darmie")
                name.set("Damilare Akinlaja")
                email.set("damilare@offbit.ai")
                organization.set("Offbit AI")
                organizationUrl.set("https://offbit.ai")
            }
        }
        scm {
            connection.set("scm:git:git://github.com/offbit-ai/reflow.git")
            developerConnection.set("scm:git:ssh://git@github.com/offbit-ai/reflow.git")
            url.set("https://github.com/offbit-ai/reflow")
        }
    }
}
